version: '3.8'

services:
  tjs:
    container_name: tjs
    build:
      context: ./app-backend
      dockerfile: ./Dockerfile
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    env_file:
      - ./app-backend/.env

  victoria-metrics:
    container_name: victoria-metrics
    image: 'victoriametrics/victoria-metrics:latest'
    ports:
      - '8428:8428'
    volumes:
      - './app-backend/infra/victoria-metrics/prometheus.yaml:/etc/prometheus/prometheus.yml'
    command:
      - '--promscrape.config=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  grafana:
    container_name: grafana
    image: 'grafana/grafana:10.1.5'
    ports:
      - '4000:3000'
    volumes:
      - './app-backend/infra/grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml'
      - './app-backend/infra/grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml'
      # - './ext/grafana/dashboards:/etc/dashboards'
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
      GF_INSTALL_PLUGINS: 'https://github.com/VictoriaMetrics/grafana-datasource/releases/download/v0.7.0/victoriametrics-datasource-v0.7.0.zip;victoriametrics-datasource'
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: 'victoriametrics-datasource'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  jaeger:
    container_name: jaeger
    image: 'jaegertracing/all-in-one:1.57'
    ports:
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '9411:9411'
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: ':9411'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
