global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'tjs-local'
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          namespace: local
          container: tjs
          environment: local
          pod: tjs-conf
